services:
  mysql:
    image: mysql:8.0
    container_name: mars_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mars_rover_sim
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # - ./database/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql

volumes:
  mysql_data:
